@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ": LogicManager" as LogicManager LOGIC_COLOR
participant ": AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ": AddCommandParser" as AddCommandParser LOGIC_COLOR
participant "a:AddCommand" as AddCommand LOGIC_COLOR
participant ": CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ": Model" as Model MODEL_COLOR
participant "p:Person" as Person MODEL_COLOR
end box

-> LogicManager : execute(add ...)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(add ...)
activate AddressBookParser

create AddCommandParser
AddressBookParser -> AddCommandParser
activate AddCommandParser
return

AddressBookParser -> AddCommandParser : parse(...)
activate AddCommandParser

create Person
AddCommandParser -> Person : new Person("Bob", "email@email.com", "999")
activate Person
return p

create AddCommand
AddCommandParser -> AddCommand : new AddCommand(p)
activate AddCommand





return a

AddCommandParser --> AddressBookParser : d
deactivate AddCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddCommandParser -[hidden]-> AddressBookParser
destroy AddCommandParser



LogicManager -> AddCommand : execute()
activate AddCommand

AddCommand -> Model : addPerson(p)
activate Model
return

create CommandResult
AddCommand -> CommandResult
activate CommandResult
return

return result
@enduml
