@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePersonList
AddressBook *-right-> "1" UniqueInterestList
UniqueInterestList -[hidden]down- UniquePersonList
UniqueInterestList -[hidden]down- UniquePersonList

UniqueInterestList *-right-> "*" Interest
UniquePersonList -right-> Person

Person -right-> InterestsList
InterestsList -up-> "*" Interest

Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Address
Person *--> Gender
Person *--> Age

@enduml
