@startuml
start
:User executes display command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

:AddressBookParser parses the command;
:DisplayCommandParser creates a new DisplayCommand;
if () then ([command is valid])
    : LogicManager executes the DisplayCommand and
                  obtains index of contact to be displayed;
    : UiManager communicates with MainWindow;
        : MainWindow displays the details of the selected
        contact in the PersonCard;
else ([else])
    : Outputs an error message;
endif
stop
@enduml
