@startuml
'https://plantuml.com/activity-diagram-beta

start
- ....
-Import person created based \non  Csv row detail

-Import person to be\nadded in  model
if () then (**No duplicates** of \n**import person** \nin  database)
    :Import Person is added into\ndatabase;
else (**Duplicates of import** \n**person** found \nin  database)
      if () then (Import has \nbeen  called)
        :Update duplicate  in  \ndatabase  to called  status;
      else (Import has not  been  called)
      endif
endif
- ....
stop

@enduml
