
@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Interface UserPrefsStorage <<Interface>>
Class JsonUserPrefsStorage
}

Interface Storage <<Interface>>
Class StorageManager

package "AddressBook Storage" #F4F6F6{
Interface AddressBookStorage <<Interface>>
Class JsonAddressBookStorage
Class JsonSerializableAddressBook
Class JsonAdaptedPerson
Class JsonAdaptedInterest
}

package "ImportExport Storage" #F4F6F6{
Interface ImportExport <<Interface>>
Class CsvAddressBookImportExport
Class CsvAdaptedPerson
Class CsvAdaptedInterest
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" AddressBookStorage
StorageManager -down-> "1" ImportExport

Storage -down-|> UserPrefsStorage
Storage -down-|> AddressBookStorage
Storage -down-|> ImportExport

CsvAddressBookImportExport .up.|> ImportExport
CsvAddressBookImportExport  --> "*" CsvAdaptedPerson
CsvAdaptedPerson  --> "*" CsvAdaptedInterest

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonAddressBookStorage .up.|> AddressBookStorage
JsonAddressBookStorage ..> JsonSerializableAddressBook
JsonSerializableAddressBook --> "*" JsonAdaptedPerson
JsonAdaptedPerson --> "*" JsonAdaptedInterest

@enduml
